# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: PyPI Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Run PyPI Release CI workflow
      uses: adafruit/workflows-circuitpython-libs/release-pypi@main
      with:
        pypi-username: ${{ secrets.pypi_username }}
        pypi-password: ${{ secrets.pypi_password }}
